Add theme selection.

diff --git a/createapp b/createapp
--- a/createapp
+++ b/createapp
@@ -107,18 +107,22 @@ create_new_app_pane() {
     gedit "$app_directory/uninstall" &
 }
 
-show_createapp() {
-    selected_action=$(yad --width="400" --height="200" \
-        --title="Create App" \
-        --text="Choose an action:" \
-        --button="Create New App:1" \
-        --button="Cancel:2" \
-        --center --on-top)
+import_zip_file() {
+    import_file=$(yad --file-selection --title="Select Zip File to Import" --width="400" --center --on-top)
 
-    case $? in
-    1) select_category_pane ;;
-    *) exit ;;
-    esac
+    if [ -z "$import_file" ]; then
+        yad --error --title="Error" --text="No file selected for import." --center --on-top --borders=10
+        return
+    fi
+
+    unzip "$import_file" -d "$APP_STORE_DIRECTORY"
 }
 
-show_createapp
+if [ "$1" == "create" ]; then
+    select_category_pane
+elif [ "$1" == "import" ]; then
+    import_zip_file
+else
+    echo "Invalid argument. Please provide 'create' or 'import'."
+    exit 1
+fi
